default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  adapter: postgresql
  encoding: unicode
  database: payment_development
  pool: 5
  username: payment
  password: password1
test:
  adapter: postgresql
  encoding: unicode
  database: payment_test
  pool: 5
  username: payment
  password: password1
production:
  <<: *default
  database: payment_production
  username: payment
  password: <%= ENV['PAYMENT_DATABASE_PASSWORD'] %>
